import Head from "next/head";

import Example from "@/components/Example";
import UserInfo from "@/components/UserInfo";
import { useAppBridge } from "@/hooks";

interface User {
  id: number;
  friendly_name: string;
}

interface UserInfo {
  user: User;
}

export default function Home() {
  const { completed } = useAppBridge({ oauth: true, type: "space-plugin" });

  return (
    <>
      <Head>
        <title>Storyblok Next Tool Starter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {completed && (
          <div>
            <p>Authenticated!</p>
            <UserInfo />
            <Example />
          </div>
        )}
      </main>
    </>
  );
}
